### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by goodstemy** [acravenho/poaexplorer.com#1]
Hello! 

I want to use this project for something really cool, but I can't create migrations to my MySQL database. Is there a way to make migrations without writing PHP code? 

For now, I got this error: 

> A Database Error Occurred
> Error Number: 1146

> Table 'poaexplo_data.wallets' doesn't exist

> SELECT SUM(balance) AS totalBalance FROM `wallets` WHERE `exclude` =0

> Filename: models/Api_model.php

> Line Number: 178

**Comment by osouza-de** [comment]
I think this project isn't mean to be "all public" in terms that we have no access to the database files.
But you can easily create the database by reverse engineering [api model](https://github.com/acravenho/poaexplorer.com/blob/master/application/models/Api_model.php).

Or you can see if [this project's database](https://github.com/poanetwork/blockscout) works here.
