### ISSUE TITLE
Contract source code cuts off

### ISSUE THREAD

**Issue by SiddigZeidan** [acravenho/poaexplorer.com#2]
When viewing the contract source code, it does not show the whole block of code, but it seems to cut off.

https://poaexplorer.com/address/0xec78bde2db6da335e04cfa7ed80373dbfb0cd502

![image](https://user-images.githubusercontent.com/4807398/40502522-3ba7f0a2-5f59-11e8-8b95-9aadea897d01.png)

**Comment by acravenho** [comment]
I'll get it sorted out today!

**Comment by acravenho** [comment]
Odd, the `<` sign in the source code broke the `pre` box. I have a temporary fix for now. I will look further into a solution this weekend.
